# Your Solution
version: '3.8'

services:
  # Service for the book_catalog microservice
  book_catalog:
    image: book_catalog
    build:
      context: ./book_catalog  # Path to book_catalog directory
    container_name: book_catalog
    ports:
      - "8000:8000"
    environment:
      - PORT=80
      - STORAGE_ACCOUNT_NAME=${project3}
      - STORAGE_ACCESS_KEY=${}
    restart: "no"

  # Service for the inventory_management microservice
  inventory_management:
    image: inventory_management
    build:
      context: ./inventory_management  # Path to inventory_management directory
      dockerfile: Dockerfile
    container_name: inventory_management
    ports:
      - "8001:8001"
    environment:
      - PORT=80
      - STORAGE_ACCOUNT_NAME=${project3}
      - STORAGE_ACCESS_KEY=${}
    restart: "no"
